// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsSuccess(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_SUCCESS.String() && e.Code == 200
}

func ErrorSuccess(format string, args ...interface{}) *errors.Error {
	return errors.New(200, UserErrorReason_SUCCESS.String(), fmt.Sprintf(format, args...))
}

func IsUnknowError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_UNKNOW_ERROR.String() && e.Code == 200
}

func ErrorUnknowError(format string, args ...interface{}) *errors.Error {
	return errors.New(200, UserErrorReason_UNKNOW_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_NOT_FOUND.String() && e.Code == 200
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(200, UserErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}
